spring:
  datasource:
    url: jdbc:mysql://localhost/prova?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    database: prova
    username: root
    password: drogaria
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    idleTimeout: 120000
    maximumPoolSize: 10
    minimumIdle: 2
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  config:
    activate:
      on-profile: producao
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

server:
  port: 8080
debug: false

---

spring:
  datasource:
    url: jdbc:mysql://localhost/prova-testes?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    database: prova-testes
    username: root
    password: drogaria
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    idleTimeout: 120000
    maximumPoolSize: 10
    minimumIdle: 2
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  config:
    activate:
      on-profile: teste

server:
  port: 8080
debug: false